# NumPy, SciPy

Les paquets NumPy et Scipy permettent de faire de nombreuses opérations sur les nombres, sur les tableaux, etc. 

* NumPy contient énormément de fonctions de base pour manipuler des nombres, des vecteurs, des matrices, ... elle définit notamment beaucoup de fonctions mathématiques usuelles, `sin`, `cos`, `exp`, etc.
* SciPy est plus axé sur les fonctions spéciales (Bessel, Lambert, Zeta de Riemann, ...) et le traitement de signal ; ce module vous permettra de faire des interpolations linéaires, des filtrages, etc.

## NumPy

### Généralités

Nous avons brièvement importé le paquet Numpy dans le [tutoriel 4](./Tutorial_4_Imports_functions.ipynb) afin de permettre de diviser une liste d'entiers par un nombre de manière efficace et pratique, alors que ces opérations ne fonctionnent pas sur des objets `list`. Mais NumPy contient beaucoup d'autres choses, notamment : 

* Des définitions pour quasiment toutes les fonctions usuelles, y compris les fonctions hyperboliques et leurs réciproques (par exemple `arctanh`)
* Des méthodes permettant de créer des vecteurs et des matrices, puis ensuite de les manipuler. Les amateurs de MATLAB seront heureux de les retrouver :-)
* Quelques 

### Les objets `np.ndarray`

Nous l'avons brièvement aperçue précédemment. Quand les éléments des `np.ndarray` sont des nombres, les `np.ndarray` représentent des vecteurs, des matrices ou même des tenseurs d'ordre (de dimension) plus élevée. Ils fonctionnent presque comme les listes, et toute la syntaxe associée va donc leur ressembler fortement, __hormis leur comportement avec les opérateurs usuels (+, *, -, / et **) et leur indexation__. On crée de tels objets assez simplement par exemple à partir d'une liste et de la fonction `np.array()`: 


In [20]:
import numpy as np
x = np.array([3,4,5])

print(x)
print(type(x))

[3 4 5]
<class 'numpy.ndarray'>


#### Indexation et _coupes_

Les `np.ndarray` s'indexent d'une manière différente que les objets `list` en Python. Pour les tableaux à une dimension, toutefois, rien de bien méchant, on peut facilement récupérer un élément, ou une _coupe_ ([cf Tutoriel 2](./Tutorial_2_ListsTuplesDicts.ipynb#Coupes)) et les résultats sont identiques à ceux obtenus pour les listes :

In [68]:
my_list = [1,2,6,9,11,-3]
my_array = np.array(my_list)
print(my_list[5])
print(my_array[5])
print(my_list[2:4])
print(my_array[2:4])

-3
-3
[6, 9]
[6 9]


Maintenant, _supposons_ que j'aie une liste de 3 listes contenant chacune 3 nombres. Ma liste de listes peut être vue comme une matrice $3 \times 3$. Je voudrais faire une _coupe_  de cette matrice et ne garder que le bloc $2\times 2$ correspondant au nombres 'en bas à droite' de la matrice initiale. Il sera difficile pour moi d'extraire l

In [64]:
mylist_of_lists = [[1,7,2],[3,4,5],[6,7,8]]
my_matrix = np.array(mylist_of_lists)

print(mylist_of_lists[1:3])

[[3, 4, 5], [6, 7, 8]]


#### Attention avec les opérations avec les scalaires !

__Contrairement__ aux listes à nouveau, la multiplication et l'addition de scalaires à un `np.ndarray` fonctionnent également comme sous MATLAB, et ce quel que soit la 'dimension' du tableau: 
* Pour `+` et `-`, on ajoute (soustrait) donc à chacun des éléments du tableau le scalaire en question
* Pour `*` et `/`, on multiplie (divise) donc chacun des éléments du tableau par le scalaire en question
* Pour `**`, on met chacun des éléments du tableau à la puissance en question (__le `.^` de MATLAB__ !)

In [23]:
vector = np.array([3,6,1])
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(vector + 3.15)
print(-5.7*vector)
print(-2.1*matrix + 6.32)
print(matrix**2)

[6.15 9.15 4.15 8.15 5.15]
[-17.1 -34.2  -5.7 -28.5 -11.4]
[[  4.22   2.12   0.02]
 [ -2.08  -4.18  -6.28]
 [ -8.38 -10.48 -12.58]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


Quand les tableaux ont des dimensions compatibles, on peut les multiplier entre eux, et par défaut cette multiplication se fait _élément par élément_ (le `.*` préféré des amateurs de MATLAB) : 


In [39]:
vector_1 = np.array([3,6,2])
vector_2 = np.array([6,4,1])
matrix = np.array([[1,1,1],[1,1,1],[1,1,1],[2,2,2]])

print(vector_1*vector_2)
print(vector_1*matrix)

[18 24  2]
[[ 3  6  2]
 [ 3  6  2]
 [ 3  6  2]
 [ 6 12  4]]


* Dans le premier cas, le comportement est assez logique, on multiplie les éléments de chaque vecteur 'un par un'.
* Dans le deuxième cas, NumPy a automatiquement cherché une dimension de `matrix` dont la longueur (3) est compatible avec celle (3) de `vector_1`, et ici, c'est la dimension n°2 (les colonnes). NumPy va ensuite _étendre_ `vector_1` dans l'autre dimension (ou les autres dimensions) pour obtenir la même forme que `matrix`, et enfin multiplier un par un les éléments de `matrix` et de `vector_1` étendu. 

#### Dimensions 

On peut demander à NumPy de renvoyer les propriétés de forme de ces objets en question, en utilisant les fonctions : 
* `np.shape()` : va renvoyer la longueur d'un tableau dans chacune des dimensions de celui-ci
* `np.size()` : va renvoyer le nombre d'éléments total du tableau
* `np.ndim()` : va renvoyer le nombre de dimensions du tableau 

In [42]:
tensor = np.array([[[1,2],[2,3]],[[12,14],[15,19]],[[-2,-1],[-3,-6]]])
print(np.shape(tensor))
print(np.size(tensor))
print(np.ndim(tensor))

(3, 2, 2)
12
3


__Mini-quiz__: 
* Que renvoie la commande `len(tensor)` ? Comment interprétez-vous le résultat ?
* Essayez de re-créer les fonctions `np.size()` et `np.ndim()` à partir de `np.shape()` en utilisant des fonctions Python et des fonctions Numpy, par ex. `np.sum()`

On peut assez facilement rajouter des dimensions en exécutant la fonction `np.atleast_nd()` (avec $n = 1,2,3$). En fonction de la dimension de votre tableau initial, les dimensions _en plus_ ne seront pas forcément rajoutées là où vous vous y attendez ! Voyez par exemple, pour un tableau à une dimension (un vecteur) transformé en tableau à trois dimensions :

In [49]:
x = np.array([1,2,6,8,2])
y = np.atleast_2d(x)
z = np.atleast_3d(x)
print(np.shape(x))
print(np.shape(y))
print(np.shape(z))

(5,)
(1, 5)
(1, 5, 1)


Vous pouvez également rajouter _à la main_ des dimensions en plus dans votre tableau en l'indexant a

In [51]:
matrix = np.array([[1,2,3],[6,5,4]])
matrix[:,np.newaxis,:]

array([[[1, 2, 3]],

       [[6, 5, 4]]])

In [53]:
x = [[2,3],[4,5],[6,7]]
x[:,:]

TypeError: list indices must be integers or slices, not tuple